name: My Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Build done"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: echo "Tests passed"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy
        run: |
          echo "Secret value is: $AWS_ACCESS_KEY"
          echo "Deployed successfully"
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
